"""post full text search

Revision ID: 021e2d0a467d
Revises: 89310065a494
Create Date: 2026-09-24 15:28:26.680499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '021e2d0a467d'
down_revision: Union[str, Sequence[str], None] = '89310065a494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', content)", persisted=True), nullable=True))
    op.create_index('ix_posts_content_tsv', 'posts', ['content_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_content_tsv', table_name='posts', postgresql_using='gin')
    op.drop_column('posts', 'content_tsv')
    # ### end Alembic commands ###
